title: 学术研讨班资料库
description: 收集和展示学术研讨班的周报、演示文稿和摘要
baseurl: "/ahu-vr-vision-seminars" # 根据您的GitHub仓库名称设置
url: "https://linbowang.github.io" # 您的GitHub Pages URL

# 启用递归处理_posts子目录
include:
  - _posts/*.md        # 匹配 _posts 目录直接下的 .md 文件
  - _posts/*.markdown  # 匹配 _posts 目录直接下的 .markdown 文件
  - _posts/**/*.md     # 匹配 _posts 子目录中的 .md 文件
  - _posts/**/*.markdown  # 匹配 _posts 子目录中的 .markdown  文件
  - _meetings/*.md     # 匹配 _meetings 目录下的 .md 文件
  - _meetings/*.markdown  # 匹配 _meetings 目录下的 .markdown 文件
  - _meetings/**/*.md     # 匹配 _meetings 子目录中的 .md 文件
  - _meetings/**/*.markdown  # 匹配 _meetings 子目录中的 .markdown  文件

# 构建设置
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 集合设置
collections:
  meetings:
    output: true
    permalink: /meetings/:year/:month/:day/:title/
  members:
    output: true
    permalink: /members/:path/

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# 社交媒体设置（可选）
# github_username: your-github-username
# twitter_username: your-twitter-username

# 集合设置
collections:
  seminar_topics:
    output: true
    permalink: /topics/:path/
    
# 默认设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "seminar_topics"
    values:
      layout: "topic"
  - scope:
      path: ""
    values:
      layout: "default"
